# Generated by Django 3.1.7 on 2021-03-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210331_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avail_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
