# Generated by Django 3.1.7 on 2021-04-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
    ]
