# Generated by Django 3.1.7 on 2021-04-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210331_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='returned_date',
            field=models.DateTimeField(),
        ),
    ]
