# Generated by Django 3.1.7 on 2021-04-06 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_auto_20210406_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ratings',
            new_name='rating_b',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('book_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('who_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
