# Generated by Django 3.1.7 on 2021-04-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210406_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='avail_qty',
        ),
    ]
