# Generated by Django 3.1.7 on 2021-04-06 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_remove_book_avail_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='who_borrowed',
            field=models.ForeignKey(default='9c495b90-3900-43d1-875d-6b15d5d5ab55', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Quantities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qty', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
