# Generated by Django 3.1.7 on 2021-04-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210406_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed',
            name='has_returned',
        ),
    ]
