# Generated by Django 3.1.7 on 2021-04-06 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0011_borrowed_has_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='who_borrowed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
