# Generated by Django 3.1.7 on 2021-04-08 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0020_auto_20210408_1033'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowed',
            unique_together={('who_borrowed', 'name')},
        ),
    ]
