# Generated by Django 3.1.7 on 2021-04-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20210408_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_Quantities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
