# Generated by Django 3.1.7 on 2021-04-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_total_quantities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total_Quantities',
        ),
    ]
