# Generated by Django 3.1.7 on 2021-04-08 16:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0024_person_quantity_const'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person_Quantity_const',
            new_name='Quantity_Borrowed',
        ),
    ]
