# Generated by Django 3.1.7 on 2021-04-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20210408_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='total_qty',
            field=models.PositiveIntegerField(),
        ),
    ]
