# Generated by Django 3.1.7 on 2021-04-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_auto_20210408_1833'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowed',
            unique_together=set(),
        ),
    ]
