# Generated by Django 3.1.7 on 2021-04-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_auto_20210408_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quantity',
            new_name='Quantity_Books',
        ),
    ]
