# Generated by Django 3.1.7 on 2021-04-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_auto_20210409_1859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quantity_Books',
            new_name='Quantity_Book',
        ),
    ]
