# Generated by Django 3.1.7 on 2021-04-18 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_auto_20210417_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('isbn', 'name')},
        ),
    ]
