# Generated by Django 3.1.7 on 2021-04-18 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_auto_20210418_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
    ]
