# Generated by Django 3.1.7 on 2021-04-20 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0037_auto_20210418_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed',
            name='who_issued',
            field=models.ForeignKey(default='9c495b90-3900-43d1-875d-6b15d5d5ab55', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='who_issued', to=settings.AUTH_USER_MODEL),
        ),
    ]
